### ISSUE TITLE
Suggestion: Move content from `introduction.md` to `README.md`

### ISSUE THREAD

**Issue by glenjarvis** [EzequielBruni/Rocky-Linux-Documentation-Style-Guide#1]
Currently `README.md` is empty with "This is a WIP".

At the same time, the main introductory content is already populated in `introduction.md` with conduct that stands-up pretty well as a `README.md`.

If there is a need for more content in `README.md,` the current content can be moved to the structure that it is now. However, it may stand well remaining in the introductory pages in `README.md`.

Currently, it feels that we're doing this too soon.

**Comment by EzequielBruni** [comment]
Oh, the structure is temporary. I'm still working on the content, which will be discussed at the next video chat meeting. I should probably add some more of the samples we got recently. You're right, the intro content will be moved to README in time, but you shouldn't consider this guide to be anything close to a published work yet.

Leaving the issue open as a reminder, but deferring this issue until later.

**Comment by EzequielBruni** [comment]
Did this sooner rather than later.

**Comment by glenjarvis** [comment]
This looks much better :)
